---
name: Ansible Galaxy Role Publish
on:
  release:
    types: [released]
jobs:
  ansible-collection-build-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: publish role
        uses: robertdebock/galaxy-action@1.2.1
        with:
          git_branch: main
          galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
